### ISSUE TITLE
Firmware patch for reading the key is not working

### ISSUE THREAD

**Issue by masterxq** [yohanes/pgpemu#2]
The pgp is not sending the key or the phone is not receiving it.
I could read and flash the pgp without any problem. All md5 sums are matching and the patch applied fine too.
I redownloaded and decrypted the firmware the md5 sum matching to the patched firmware.
The problem is: The key is not part of the data.
I get:

- state [4 bytes]
- nonce [16 bytes]
- enc. main challenge [80 bytes]
- enc. hash [16 bytes]
- bt_addr [6 bytes]
- blob [256 bytes]
- end.

So no key.
I'm not sure if i maybe only get the data from the reconnect. But I did reset pogo and the pgp often.
Sadly i don't know much about the ble or bt in generally. So the problem can still be on my side. But did my best to avoid this possibility.
The pgp connecting as usual.
Maybe there is somewhere an additional length field and my phone is just cutting down the message?

Thanks for your work. It is really nice.

**Comment by yohanes** [comment]
The key should be the last 16 bytes of the BLOB (after you patched the code).

You can compare the blob before and after patching, it should be different.

**Comment by masterxq** [comment]
Thank you very much.
I think i got my key, but have to test it tomorrow.
