### ISSUE TITLE
Original spi flash can not be written

### ISSUE THREAD

**Issue by masterxq** [yohanes/pgpemu#4]
The hack writing the the SPI Flash is working fine on china devices. But not on the Orignal.
It is an unknown SPI Flash, at least i could not find any information. It identifies itself with:
id1 0x1f (vendor id normally atmel), id2 0x4200 (device id).
It is possible to read it with flashrom with the -f flag (force). Checked MD5sum after decrypting it is exactly the same Firmware image.
But it is not possible to write the Flash.
I checked the following:
- Could not find a datasheet for the spi flash. Maybe somebody knows more here.
- write protect is high... (So disable i think... No datasheet).
- I hacked the flashrom tool so it acts like it does on the china copy. (GD25Q20). It tries to write but verify will fail on one byte -> still the old image. Just changed the device id's in the source.

I have some ideas but they are a lot of work.

- Find a compatible SPI Flash and bye it. Replace the original.
- Take the Flash from a copy and solder it to the original.
- Emulate the SPI flash with the ESP32. (Maybe original chip can stay if the hold pin is held low)
- And of cause: Find a JTAG tool and use the alternative way...
Edit: Just discovered that spi flash needs to be written for JTAG too.

I think it is possible you will have the same issue with the OTA Hack. Maybe the Flash is just protected in some way and need to be handled as otp. If you want and if you don't have an original device, i can help you testing.

Regards

**Comment by masterxq** [comment]
However it is working now.
Maybe because i set very low speed for writing the flash.
The problem is the SPI Flash on the original device can not be detected by the flashrom tool. 
```
Manufactor ID: 0x1F
Chip ID Byte1: 0x42
Chip ID Byte2: 0x00
```

I have a China copy too. With a SPI Flash that identifies as:
```
GD25Q20(B)
```

As there is the same ble controller on both devices I tried to force flashrom to act identical i both cases.

What i did to force the flashrom tool to write on it:
Download source for the flashtool.
[flashrom on github](https://github.com/flashrom/flashrom)
edit flashchips.h
change this line:
```
#define GIGADEVICE_ID           0xC8
```
into:
```
#define GIGADEVICE_ID           0x1F
```


And this line:
```
#define GIGADEVICE_GD25Q20    0x4012  /* Same as GD25QB */
```
into:
```
#define GIGADEVICE_GD25Q20      0x4200
```

Compile the flashrom tool.


Then flash the SPI Flash with this command:
```
./flashrom -VVV -c "GD25Q20(B)" -p linux_spi:dev=/dev/spidev0.0,spispeed=300 -w filetoflash.bin
```
I tried with higher speed the first time. Maybe this was the problem. But don't know for sure.
You can read the flash like this:
```
flashrom -V -p linux_spi:dev=/dev/spidev0.0,spispeed=3000 -f -r filetodownload.bin
```
Reading the Flash needs no modification it can be forced.

Maybe there is a more simple way to force flashrom to act like there is a GD25Q20 SPI Flash. I'm a very bad user until i read the source and this is to much work. But this worked in my case. Maybe in your too. Good luck.

**Comment by yohanes** [comment]
Ok, I hope it can help other users that may face the same problem.

**Comment by sabas1080** [comment]
@masterxq what version of flashroom use?

**Comment by masterxq** [comment]
I think i cloned the latest from the repo at the day i wrote. But not completely sure. Always doing stuff like this in /tmp/ so can not tell you for sure.
