### ISSUE TITLE
undefined references

### ISSUE THREAD

**Issue by MarcoKull** [yohanes/pgpemu#5]
When I try to build the esp project I get a lot of "undefined reference" errors.
You can solve this just by adding all the .c files to the COMPONENT_SRCS in pgpemu/pgpemu-esp32/main/CMakeLists.txt like this:

`set(COMPONENT_SRCS "aes.c  cert-test.c  pgp-cert.c  pgpemu.c  secrets.c")`

Once it compiled it works like a charm, thanks so much for this example implementation!

**Comment by yohanes** [comment]
I do not have this problem, but this is good to know in case someone else has the same problem.

**Comment by krasny2k5** [comment]
This happened to me also, compiling using ESP-IDF 3.3.2 on ubuntu linux. The @MarcoKull's solution solved the problem. Thank you!
