### ISSUE TITLE
fatal error: hwcrypto/aes.h: No such file or directory and switching to another library

### ISSUE THREAD

**Issue by disable-0001** [yohanes/pgpemu#6]
Hi,
I'm using an esp8266 nodemcu v3.

Getting an issue while flashing, since this seems for esp32 only I think hwcrypto cannot be found on the SDK of esp8266. Searched for another library and found out mbedtls but now im running with this error because it cannot recognize the variable. Which one should I put in order to make it compatible with my board? Thanks.

Line changed: #include "mbedtls/aes.h" on pgp-cert.h line 8

Logs when flashing:
> C:/msys32/home/Javi/esp/pgpemu/pgpemu-esp32/main/pgp-cert.h:10:21: error: unknown type name 'esp_aes_context'
>  #define AES_Context esp_aes_context
>                      ^
> C:/msys32/home/Javi/esp/pgpemu/pgpemu-esp32/main/pgp-cert.h:46:17: note: in expansion of macro 'AES_Context'
>  void aes_setkey(AES_Context *ctx, const uint8_t *key);
>                  ^
> C:/msys32/home/Javi/esp/pgpemu/pgpemu-esp32/main/pgp-cert.h:10:21: error: unknown type name 'esp_aes_context'
>  #define AES_Context esp_aes_context
>                      ^
> C:/msys32/home/Javi/esp/pgpemu/pgpemu-esp32/main/pgp-cert.h:48:15: note: in expansion of macro 'AES_Context'
>  void aes_hash(AES_Context *ctx,
>                ^
> C:/msys32/home/Javi/esp/pgpemu/pgpemu-esp32/main/pgp-cert.h:10:21: error: unknown type name 'esp_aes_context'
>  #define AES_Context esp_aes_context
>                      ^
> C:/msys32/home/Javi/esp/pgpemu/pgpemu-esp32/main/pgp-cert.h:54:14: note: in expansion of macro 'AES_Context'
>  void aes_ctr(AES_Context *ctx,
>               ^
> C:/msys32/home/Javi/esp/pgpemu/pgpemu-esp32/main/pgp-cert.h:10:21: error: unknown type name 'esp_aes_context'
>  #define AES_Context esp_aes_context
>                      ^
> C:/msys32/home/Javi/esp/pgpemu/pgpemu-esp32/main/pgp-cert.h:60:20: note: in expansion of macro 'AES_Context'
>  void encrypt_block(AES_Context *ctx,
>                     ^
> C:/msys32/home/Javi/esp/pgpemu/pgpemu-esp32/main/pgp-cert.h:10:21: error: unknown type name 'esp_aes_context'
>  #define AES_Context esp_aes_context
>                      ^
> C:/msys32/home/Javi/esp/pgpemu/pgpemu-esp32/main/pgp-cert.h:65:14: note: in expansion of macro 'AES_Context'
>  void aes_ctr(AES_Context *ctx,
>               ^
> cc1.exe: warning: unrecognized command line option '-Wno-frame-address'
> make[1]: *** [/home/Javi/esp/ESP8266_RTOS_SDK/make/component_wrapper.mk:292: cert-test.o] Error 1
> make: *** [C:/msys32/home/Javi/esp/ESP8266_RTOS_SDK/make/project.mk:571: component-main-build] Error 2

**Comment by yohanes** [comment]
ESP8266 doesn't have BLE, only Wifi, so I am not sure why you are trying this on ESP8266
