### ISSUE TITLE
PGP-EMU not Connecting to specific Phone

### ISSUE THREAD

**Issue by BMOtheConsole** [yohanes/pgpemu#7]
ERROR Description:
PGP-EMU is working with my Samsung Galaxy S7 but not with my Huawei P20 Pro because Timeout is probably to short.

How i got it working on my PGP:
On my original PGP, to connect it successfully, i need to press the Button again after it stopped blinking Blue. 

ERROR LOG:
I (177501) PGPEMU: ESP_GATTS_DISCONNECT_EVT, reason = 34
I (177511) PGPEMU: advertising start successfully
I (198471) PGPEMU: ESP_GATTS_CONNECT_EVT, conn_id = 0
I (198481) PGPEMU: 4d bd 7f a9 f4 7e 
I (200481) PGPEMU: update connection params status = 16, min_int = 16, max_int = 32,conn_int = 38,latency = 0, timeout = 500
E (229111) BT_BTM: btm_proc_smp_cback received for unknown device
W (238561) BT_BTM: btm_sec_clr_temp_auth_service() - no dev CB

W (238561) BT_BTM: btm_sec_clr_temp_auth_service() - no dev CB

E (238571) BT_BTM: btm_proc_smp_cback received for unknown device
E (238571) BT_BTM: Device not found

**Comment by DebugDax** [comment]
Did you find a solution to this since you closed the issue?
I'm running into the same thing.
